version: '3.8'

services:
  markdown-editor:
    build:
      context: .
      dockerfile: Dockerfile
    image: markdown-editor-app
    container_name: markdown-editor-container
    ports:
      - "3030:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
